alert("click anywhere to play the bad apple");

const letters = [
  `        Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum fuga, officia iure eos quibusdam nam blanditiis voluptates necessitatibus laudantium aperiam ut itaque reprehenderit et facilis inventore cumque debitis consequatur libero?
        Temporibus earum eaque dignissimos nulla. Repellendus totam natus fugiat consequuntur, corporis praesentium numquam obcaecati sapiente adipisci perspiciatis? Labore nesciunt dicta commodi quasi, est dolorem fugit explicabo non magni mollitia omnis!
        Architecto molestias rem, sunt debitis labore praesentium tempore rerum tenetur aliquid, veniam magni at dicta, inventore illo quo saepe natus maiores aliquam ipsum unde repudiandae dolores fugiat reprehenderit neque? Necessitatibus.
        Vitae reiciendis praesentium eaque! Porro, delectus neque omnis incidunt accusamus adipisci labore. Illum laboriosam aspernatur magni officiis atque. Exercitationem rerum doloremque praesentium voluptatem temporibus repellat est, harum blanditiis quo consequatur?
        A ad praesentium culpa qui id adipisci magni corporis magnam, unde quaerat impedit fugiat delectus hic dolores est tempore repellat nostrum modi consequatur! Similique, harum hic cupiditate facilis velit dignissimos.
        Officia ipsam fuga fugiat, sit veritatis magnam facere beatae velit laborum fugit earum inventore minima quod accusamus cupiditate doloremque placeat sunt necessitatibus voluptatum? Quae neque debitis corrupti esse fugiat quam?
        Sunt dolorum sapiente illum consectetur aliquam quasi sint, perspiciatis asperiores ipsa. Minima nisi porro nulla repudiandae magni soluta eius, quidem, dicta iusto illo delectus dolorum minus voluptate voluptatum, placeat quo.
        Doloremque doloribus neque minima, eveniet illo porro! Blanditiis est quaerat consequatur ab dolorem perspiciatis incidunt repudiandae deserunt distinctio ullam ipsum atque accusamus minima quos sit odit, sunt nam, consectetur veniam?
        Vel impedit praesentium animi unde iusto sapiente alias vitae! Reprehenderit officiis accusamus eius quia, et aliquid molestias eveniet quidem repudiandae quasi vel placeat veritatis voluptatibus fuga facere debitis libero quas?
        Quisquam dignissimos ipsam tempora minus praesentium earum, temporibus a ullam officia nesciunt alias recusandae pariatur, sequi, vitae fugiat eum aliquam blanditiis! Aperiam beatae tempora rerum repudiandae autem possimus animi explicabo.
        Provident voluptas hic vel fuga accusamus unde aspernatur perspiciatis at odit temporibus alias consequuntur, repudiandae dolor doloribus quod repellat? Voluptate cupiditate commodi placeat inventore neque, quia illo! Vero, temporibus quam.
        Dolor, minima impedit sit totam labore possimus quae officiis laborum illo natus sunt optio! Eum, culpa possimus. Quaerat perspiciatis iusto facilis ipsum minus voluptatibus! Accusantium optio incidunt iusto adipisci officia?
        Illum at, corporis sint id aliquid cumque assumenda voluptatem quo natus dicta minus debitis nesciunt nihil maxime? Quae ratione atque animi nam. Dolor deserunt error saepe voluptate labore exercitationem eveniet.
        Beatae eaque dolorum dicta, nam perspiciatis non praesentium eveniet animi culpa quibusdam totam repellendus incidunt quisquam commodi laudantium libero eius aspernatur quaerat, illum voluptatem doloremque doloribus temporibus minus. Minima, accusantium.
        Illum eaque mollitia similique aperiam ipsa vitae impedit esse necessitatibus doloribus? Ducimus provident dignissimos aspernatur illo nam, similique aut consectetur, quas dolore sequi amet fuga ipsum reiciendis veniam autem beatae.
        Fuga voluptatum, dolorem tempore illum ipsum laudantium, tenetur quidem ullam dolore maiores doloremque, et minima corporis quisquam aspernatur fugit. Sapiente explicabo eius quidem expedita! Eum distinctio a similique incidunt saepe.
        Quasi, recusandae? Explicabo earum sequi odit tempore assumenda aliquam porro nihil! Nisi voluptatibus veritatis ducimus pariatur ad atque, incidunt aperiam ut non! Non repellat quae nihil, tenetur eum placeat labore?
        Deleniti dicta, laudantium minima expedita eaque magnam, a impedit eligendi autem consequuntur in nam tempora magni. Voluptatibus obcaecati facilis placeat nostrum explicabo autem provident ratione, praesentium in aspernatur iure inventore!
        Unde maxime obcaecati, ea ipsam blanditiis necessitatibus doloremque vel veniam enim veritatis nostrum dolore asperiores quasi officiis maiores aliquam voluptate voluptates aliquid et doloribus cupiditate. Exercitationem corporis cumque ea ad?
        Enim accusamus quo laborum ipsum, rerum voluptatum officia animi ratione et, quam libero. Nihil nemo quibusdam et? Laboriosam perspiciatis, repellat sunt quod, doloremque quam beatae recusandae aliquid sapiente doloribus est?
        Incidunt aperiam pariatur natus voluptatem velit id sequi eveniet quas doloribus dicta ex vel ad quae, earum commodi animi, quod expedita eum non ipsam! Soluta consectetur officiis optio sit eaque!
        Magnam perferendis, possimus sequi sunt veniam in atque tenetur eum optio incidunt iste aspernatur debitis, ea vitae excepturi dolor nemo nisi deleniti laudantium dolorem rerum accusantium, saepe modi. Sit, labore?
        Corporis praesentium numquam necessitatibus beatae minima magnam, alias eaque blanditiis itaque eveniet deserunt cum nemo! Sapiente neque saepe doloribus exercitationem ex. Similique eveniet corrupti reiciendis ad, repellendus neque impedit numquam.
        Laborum consequuntur omnis non aperiam consequatur, hic laboriosam quod numquam aliquid tempore veniam optio cum reiciendis earum rerum! Natus atque iste odit harum laudantium error perferendis nemo esse, soluta corporis.
        Earum magnam ipsum dolores at blanditiis ipsam expedita, consequuntur, corporis hic, illum perspiciatis! Ut necessitatibus commodi quod consequuntur dolorum quibusdam ipsum quis assumenda, reiciendis iste, facilis laboriosam labore aliquam. Nihil!
        Minima aspernatur neque, odio debitis impedit quaerat a quod totam, iure repellendus optio consequuntur. Blanditiis ipsam nam, repellendus suscipit et ipsa, eum, nobis facilis provident fuga ad assumenda commodi esse.
        Exercitationem porro maxime sint cumque modi velit perferendis dicta dolor commodi nemo vero, libero perspiciatis id iste blanditiis veniam quae earum debitis reiciendis! Veniam perspiciatis repellat, iusto nihil quis atque.
        Veniam, autem accusamus. Tempore commodi, cumque reprehenderit perferendis id maiores esse, ipsam voluptatem tenetur rem ipsa asperiores recusandae est, assumenda ducimus possimus dolorem alias. Optio obcaecati doloremque quo porro sit!
        Minima quasi iusto aut consectetur in. Explicabo, cum. Modi cumque consequatur commodi autem iure? Tempora laborum rem saepe rerum sunt error ducimus, quaerat inventore possimus obcaecati? Natus fugit reprehenderit voluptatum.
        Nam vel non, maiores quibusdam nihil laudantium perferendis obcaecati quo libero sit officia quam? Nulla exercitationem eaque tempore, cum quia reiciendis incidunt dicta iste repudiandae dolor obcaecati enim totam nisi.
        Aliquam praesentium nihil placeat laborum, culpa a voluptas iusto expedita ratione excepturi repellendus pariatur illum debitis in beatae ducimus nemo consectetur quo ullam maiores labore ipsum repudiandae non. Et, ex!
        Nemo similique quas ad quis distinctio reprehenderit cum. Ab, vitae unde accusamus, nemo consequuntur, dolore amet perspiciatis sapiente eum delectus necessitatibus facilis praesentium? Ad voluptas doloribus voluptatibus illum unde placeat.
        Officiis ratione repudiandae tempore amet. Nisi nobis vitae rerum animi ab ducimus accusantium hic, placeat consequuntur voluptas harum quod veritatis, aut est? Repellat aperiam blanditiis porro explicabo, distinctio ex ut.
        Est maxime iusto amet mollitia adipisci aut illo non modi aperiam cumque natus vel molestias pariatur provident ratione quisquam explicabo nemo, aliquid sunt! Rerum, quidem sequi? Laudantium sapiente repudiandae vitae!
        Iure ipsa debitis voluptates, ipsam cupiditate est rem sequi repellendus quidem pariatur qui dolor beatae adipisci quo exercitationem reiciendis, consequatur impedit ipsum in veniam consequuntur architecto non. Cupiditate, modi nulla.
        Nisi, autem. Quae, sed quia! Ipsa blanditiis officiis nemo in, asperiores recusandae quibusdam architecto eius veritatis, autem, reiciendis velit voluptatum minus placeat aspernatur? Sint non quaerat, quod nam dignissimos atque!
        In doloribus nisi quo inventore quos. Nisi iste enim eligendi dolor deleniti hic, pariatur quam earum nostrum exercitationem incidunt! Consectetur tempora eveniet quibusdam maiores rerum commodi illo natus architecto excepturi.
        Autem facilis adipisci error, quis omnis quaerat placeat. Id est, sunt atque dolorem rerum numquam neque maiores, veniam, fugiat laborum aperiam magnam explicabo vel amet officiis sint necessitatibus labore porro!
        Omnis, iusto unde laboriosam quo ullam magnam cupiditate! Eos possimus natus aut, quod provident voluptates praesentium facilis laborum, velit laudantium quia vel repellat perferendis incidunt harum ipsum magni? Assumenda, tempora!
        Cumque amet quasi nulla corrupti sed ipsa voluptatum commodi! Assumenda illo corrupti delectus accusamus vero quae porro iste quas quo reiciendis consequatur amet tempora minima possimus nemo, corporis sit quidem.`,

  `        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Earum, laboriosam. Atque architecto incidunt iusto nesciunt consequuntur vero tempora optio natus sint dolorum, repudiandae quo assumenda eveniet doloribus, odio fugit. Ullam.
        Hic nulla iusto quaerat quae enim repellendus veritatis obcaecati numquam corporis, consectetur et tempore, aliquid quo mollitia amet rem atque sunt tenetur recusandae dolores blanditiis laudantium. Nulla nobis quo velit!
        Vero ab voluptatibus illo mollitia, fugit obcaecati eveniet odit aliquam ducimus laudantium corporis, dicta laborum, harum ad impedit! Illum vel maxime dignissimos sint tempore placeat quis itaque optio quidem voluptatibus.
        Laudantium voluptas eligendi quos nostrum, quaerat tempora laboriosam odio error numquam earum excepturi nobis odit dolor minima eum quisquam possimus quo. Ut modi exercitationem officia deserunt quae facere sequi enim?
        Ipsum quasi animi odit hic rem aperiam numquam autem, labore nam, assumenda, nostrum minima. Nesciunt pariatur excepturi quo sapiente voluptas inventore, vel ipsum tenetur fuga earum dolores, eligendi ea nemo.
        Natus optio quaerat eveniet, quisquam ullam doloremque nostrum dignissimos ratione at esse assumenda facere ex accusantium quibusdam qui aliquid vero pariatur reprehenderit maxime suscipit explicabo eaque animi? Odit, laborum quo.
        Voluptatem id ullam quasi eveniet placeat culpa omnis unde expedita temporibus cum! Rem quod aliquid iusto explicabo accusamus corrupti iste itaque, ut reiciendis officiis cum odio nemo dicta, blanditiis maxime!
        Ipsum aut possimus ad consequatur, ut magni quibusdam asperiores esse enim aspernatur eligendi illo cum aperiam libero minima impedit nisi ab suscipit natus maiores quae similique. Error tempora earum illum!
        Optio veritatis voluptate, suscipit in aliquam quis earum necessitatibus quo iusto aspernatur, temporibus recusandae. Quasi, quo commodi nesciunt sint mollitia molestias architecto inventore expedita, ipsa odio quisquam doloribus vitae voluptates!
        Nobis deserunt commodi maxime distinctio accusantium nam voluptate? Eius tempora modi sunt eveniet dolores voluptatibus officia. Porro rerum perspiciatis, optio, sequi voluptas hic consequuntur minima ut possimus temporibus voluptates est.
        Dolorem fugiat suscipit quasi, sapiente libero vero sint id dolore numquam impedit voluptates fugit distinctio illum consequuntur ullam repudiandae natus voluptate expedita. Deleniti mollitia doloremque minima quae voluptates fugiat illo.
        Praesentium voluptatem ipsum corrupti, excepturi similique pariatur sequi fuga. Voluptas cumque doloremque ullam corrupti quisquam, reiciendis mollitia cum fugiat voluptates accusantium adipisci hic, facere est assumenda, et odio expedita fuga.
        Exercitationem explicabo beatae consequatur quibusdam necessitatibus officia molestias accusamus tempore totam rerum sit incidunt suscipit nemo inventore impedit at, similique quam. Praesentium qui quisquam dolorem, unde dolorum nobis minima ipsum?
        Labore totam ipsa nostrum, soluta eligendi vero? Vel minus nisi corporis deleniti magnam necessitatibus eaque ea veniam fugiat ipsa amet perferendis repellat corrupti nemo aperiam odit omnis optio, odio esse!
        Dolorem voluptate sed temporibus deserunt excepturi nobis a nihil perferendis! Voluptate, dolorem! Non, aliquam consequuntur sequi nulla temporibus natus. Quas maxime nam fugit nemo quos ipsam neque est asperiores iure?
        Sequi, in porro? Exercitationem facilis impedit doloribus deserunt alias culpa similique eaque nemo. At nam eveniet officiis earum natus quia ullam fugit amet assumenda vero hic, vitae est, ex commodi.
        Consequatur natus nostrum repudiandae? Atque labore dicta optio? Illum, itaque. Eaque eum dolore vitae quisquam, dignissimos maxime officia nulla rem excepturi aliquid mollitia, sint quaerat quasi facere rerum recusandae modi.
        Corrupti ab harum molestias sed quia eos nisi quasi laboriosam molestiae iure porro accusantium mollitia suscipit, aliquid quaerat optio quo ex. Eaque, vero! Iure consectetur culpa repellendus fugiat nulla architecto?
        Suscipit, numquam? Ducimus sit consequuntur architecto ad! Alias itaque asperiores voluptates ex eos. Consectetur ipsa ea libero ducimus dolorem repudiandae maxime esse optio delectus quos exercitationem, sit earum cum nemo.
        Obcaecati animi laborum, aliquam voluptatibus nam inventore! Iste deserunt fugit similique commodi voluptatem accusantium ipsa pariatur dolore labore. Ad labore perspiciatis quibusdam dolorum illo optio quae architecto magni repudiandae et.
        Saepe magnam deserunt exercitationem! Cumque porro tempora esse! Obcaecati, quasi quia quos laborum impedit aliquam tempore officia adipisci hic optio nulla consectetur iure ea magni odit. Non saepe iure atque!
        At sed quas suscipit placeat debitis ut non, nihil eos cum totam, consequatur, corrupti praesentium eaque rem voluptate? Recusandae neque earum at quis blanditiis ab, cupiditate excepturi accusamus iusto saepe.
        Qui praesentium in cupiditate placeat officia repellat explicabo, quas omnis molestias id voluptatem, assumenda quo aut quasi eligendi earum. Pariatur deserunt quibusdam cum alias inventore quisquam. Reiciendis dolorem natus quae?
        Libero eaque perferendis incidunt veritatis harum temporibus beatae quod eos eligendi delectus similique vel, est voluptatum modi fuga nemo vitae quae eum ad magnam perspiciatis cumque dolorem? Quasi, eligendi alias.
        Ut asperiores quidem modi, fugit quasi atque nemo explicabo quam dolore, dolorum minus corporis adipisci exercitationem culpa dolor illo deleniti consectetur alias error? Repellendus, natus! Tempore architecto omnis quas hic.
        Numquam nobis id sunt possimus et dolorum, aliquam quasi, nostrum earum suscipit asperiores soluta voluptas in laudantium cum, ipsa ut molestiae libero illo non ullam harum vel! Adipisci, quis ratione!
        Reiciendis magni quia porro ab, enim accusantium cupiditate at consequatur amet sunt voluptas placeat omnis commodi veritatis incidunt quaerat aliquid mollitia suscipit itaque aliquam magnam obcaecati ratione? Eos, cumque ipsum?
        Quidem odit placeat animi omnis natus voluptatem suscipit libero. Amet quibusdam veniam excepturi quo consectetur officia nihil quos aliquam quas unde, praesentium perspiciatis exercitationem atque quod modi, et suscipit consequatur.
        Quo animi fuga obcaecati! Ut ipsum quasi vel aperiam, laboriosam facilis, fugiat totam quas unde voluptas suscipit error fugit numquam quaerat aliquam, at odio? Hic aut vel numquam blanditiis soluta.
        Saepe aperiam eum eos autem cumque minima accusantium, qui harum necessitatibus corporis accusamus! Non mollitia optio totam, dolores quisquam voluptatem voluptates doloribus corporis hic suscipit, quo incidunt voluptatibus culpa omnis.
        Delectus inventore tenetur maxime earum rerum, consectetur porro consequuntur iure pariatur nesciunt aperiam asperiores facere id, quasi nam. Reprehenderit nemo ad illum ducimus porro? Dicta mollitia qui officia accusamus nulla.
        Exercitationem repudiandae qui molestias blanditiis quisquam atque officia eos placeat animi obcaecati, et non? Quo quasi reiciendis dicta sed consequatur laborum ipsam ducimus? Explicabo esse atque libero fugit cum tempore?
        Aliquid earum, cupiditate eligendi excepturi, voluptate explicabo necessitatibus magni placeat ut nobis temporibus similique. Totam dolores eos consectetur sequi eligendi exercitationem, minima expedita, officiis laudantium natus eveniet eius possimus incidunt?
        At voluptatem iusto, commodi ut officiis enim ipsam assumenda, aut pariatur quaerat doloremque quia id facilis ad necessitatibus! Nisi architecto aspernatur modi numquam possimus nesciunt exercitationem id quidem optio maiores?
        Mollitia in quaerat pariatur doloremque nesciunt natus perferendis optio nihil officiis placeat est nulla delectus voluptate rem incidunt iste amet dolorem architecto facilis ab deleniti, reprehenderit temporibus enim sapiente. Dolorum.
        Eius voluptatum ullam magni numquam voluptas dicta tempore est eaque ut, amet in aut minima tempora sequi repellendus sapiente itaque aliquid nostrum quo quam doloribus obcaecati dolorem sed! Architecto, perspiciatis?
        Numquam ea a nisi. Voluptate ullam impedit ipsam quae tenetur dolore deserunt sunt nam modi distinctio totam incidunt obcaecati perferendis officiis odit dicta cum necessitatibus asperiores quia, rerum voluptatibus labore.
        Nemo labore obcaecati maiores ex commodi ipsa, nisi quae eos quo illo sequi nam quibusdam quam neque tempore asperiores! Suscipit hic accusamus asperiores doloribus, reprehenderit dolor possimus alias quam exercitationem?
        Aliquam, cupiditate commodi rem delectus eveniet quibusdam, aut consectetur repudiandae non voluptates, pariatur totam placeat tempora esse optio molestias expedita numquam in praesentium vitae. Cupiditate iure architecto quae vero odio.
        Obcaecati earum unde non magni consequatur nostrum, sint autem animi! Cupiditate libero quo minus, est corporis possimus, aspernatur nobis omnis similique cum quia velit iste nesciunt, earum temporibus. Excepturi, aliquid!`,

  `Lorem ipsum dolor sit, amet consectetur adipisicing elit. Velit nihil, libero eos sit voluptate maxime, placeat totam nobis magnam labore laboriosam neque eligendi? Suscipit saepe ullam nobis facilis ab nihil.
Vero iste quos iusto accusamus corrupti id tempora dignissimos ipsa, dolores minima quae deleniti voluptate laboriosam adipisci sint, nisi animi. Molestiae praesentium sapiente eaque nisi nesciunt facere hic in non.
Provident excepturi nihil error numquam molestiae tenetur aliquam corrupti officiis ipsum laborum. Harum, corporis architecto recusandae quod vero reiciendis distinctio cumque fuga iure cupiditate facilis omnis? Ducimus ea omnis dignissimos?
Incidunt eius unde aspernatur maiores, numquam, cupiditate vel facere iste, distinctio architecto laudantium. Est quibusdam repellendus assumenda ipsa laborum. Iste, quibusdam? Quas exercitationem enim magni mollitia? Eligendi sequi dolorem unde.
Ducimus nemo ea ad dolor necessitatibus maxime facere fugit ipsam nisi cupiditate aperiam quisquam sunt incidunt laboriosam amet eum nam asperiores voluptate, consequatur repellat rem. Quas obcaecati enim excepturi recusandae.
Atque dolorem nihil rem dolor nemo, ea reiciendis aliquam iusto doloribus facere magnam fugit provident magni aperiam! Voluptas ipsa nemo omnis quis autem cumque laudantium ullam? Pariatur ad unde temporibus!
Eveniet ut unde officiis, corrupti eius fugiat tenetur. Labore quo deserunt autem eaque et fugiat quidem nam natus, molestias sed? Totam quam unde possimus! Dignissimos aliquid totam perspiciatis fuga architecto.
Eum reprehenderit ipsum officia, accusamus laudantium ipsa mollitia, tempore odit sequi quam corporis odio beatae, repellat nam dolor illo sapiente fugiat iure veritatis deserunt aperiam expedita voluptates maiores provident. Error.
Consequuntur dolore, minima quibusdam ad magnam expedita in quidem provident tenetur accusantium repudiandae distinctio explicabo officia, vitae quos illum! Consequatur obcaecati, quod architecto blanditiis cum corporis voluptate perspiciatis. Quos, sint.
Laborum alias nihil doloribus sunt consequatur praesentium. Corporis animi est excepturi asperiores omnis nihil? Vel accusantium quasi, cumque labore illum veniam eum debitis eaque ipsa autem recusandae magnam obcaecati eius?
Molestiae at nisi aperiam eveniet nihil et expedita. Natus beatae totam, blanditiis cum, expedita facere eos eaque, recusandae est tempora a modi. Beatae minus molestiae alias ipsum iusto nobis iste!
Consectetur, debitis. Labore suscipit nesciunt, iusto distinctio reiciendis ipsa obcaecati pariatur? Illo fuga, placeat eligendi consectetur accusamus laudantium perferendis vel excepturi aut in, dolore ipsa minus quos laborum corporis esse.
Accusantium illo ipsam distinctio velit veniam nulla praesentium cumque! Eos, nihil quis reprehenderit ut beatae, corrupti suscipit sed tempora ad nobis iste dicta accusantium vitae voluptatem perferendis assumenda aliquam itaque?
Expedita tempore, ipsa sit nihil excepturi harum tenetur esse voluptatibus id dolor? Tempora at sequi culpa, fugit, quas dicta aperiam cumque voluptatibus voluptas facilis dolor architecto corporis beatae. Reprehenderit, facilis.
Libero odit nostrum error, consequuntur rerum temporibus, totam nisi sit quas dolorum, deserunt repudiandae praesentium maxime aperiam accusamus voluptatum? Ipsam, fuga reprehenderit inventore voluptate odio accusamus eveniet iste exercitationem doloremque?
Reiciendis, eos labore? Excepturi perspiciatis modi et blanditiis ea laudantium. Excepturi fugiat adipisci minus totam mollitia nihil in repudiandae nobis perspiciatis voluptas hic quasi cumque, nulla perferendis amet consectetur possimus?
Cum aspernatur magni nisi, a natus fugiat? Vitae sed, natus delectus consectetur maiores dolore! A, corrupti et iure at nisi doloribus, in similique suscipit aperiam consectetur adipisci, labore eligendi eveniet?
Neque magnam veniam labore laborum error, aliquam corporis itaque placeat illo adipisci? Quam itaque odit laborum suscipit vero. Quibusdam nobis earum molestias consectetur magni debitis cum non sit, officiis perferendis.
Natus quaerat quisquam odit. Dicta pariatur reiciendis ex? Reprehenderit repudiandae nisi molestiae consectetur, dolorem, voluptas possimus, ducimus laudantium dolorum sapiente rem ex vero maiores! Repellendus maxime autem voluptatibus ullam quisquam!
A maxime inventore ad laborum! Debitis natus expedita, rem porro voluptatum ipsam praesentium amet rerum iusto. Eligendi velit vero consequatur magnam autem molestiae voluptatum nobis expedita numquam eaque. Excepturi, ducimus?
Eos ad, cupiditate ipsum voluptas adipisci fuga non sequi velit minus accusantium praesentium ipsa odio molestiae hic eum neque ea incidunt expedita. Ad sunt molestiae incidunt amet officiis recusandae dolorem!
Modi iusto culpa quos explicabo voluptatibus, iure consequuntur minima quisquam consectetur eveniet delectus, harum fuga sapiente accusantium neque, atque perferendis impedit tempora. Animi consequuntur eius laborum rem officiis, doloremque illo?
Tenetur facilis reiciendis dolore dignissimos, distinctio aliquam, natus suscipit eligendi molestiae officia reprehenderit soluta placeat iure laboriosam totam! Magnam neque veritatis architecto doloribus odit expedita, adipisci quae voluptate voluptas? Voluptatem.
Ipsam fugiat totam voluptate doloremque quia accusamus sed aut molestias quam omnis! Pariatur illum, inventore laudantium aspernatur perspiciatis sit fugit sed numquam corrupti animi odit, natus laboriosam, ratione placeat fuga.
Ut fugit quisquam, saepe dolore sapiente maxime ipsa necessitatibus eligendi, iusto eum quam recusandae placeat dolorem temporibus? Nam, nesciunt obcaecati? Autem itaque est provident cumque, repellendus vel recusandae veniam quas!
Nostrum neque aliquid voluptas exercitationem excepturi accusantium quis illo, quisquam repellendus praesentium. Ipsam dolorem, excepturi ex laborum, ratione quas harum laudantium autem dolor consectetur molestias tempora iusto omnis dicta veritatis!
Earum voluptatem voluptates possimus excepturi quia eum inventore! Corporis, hic. Quam ea expedita hic tenetur tempore porro numquam doloremque, animi nesciunt vitae eveniet culpa labore consectetur assumenda blanditiis necessitatibus repellat.
Maiores eligendi modi aperiam eaque debitis vitae iure iste asperiores accusamus dolorum minus sapiente unde facilis hic aut ipsum odio quae tempora magnam perferendis, delectus, reprehenderit nulla deserunt? Beatae, quasi!
Provident quo sapiente cum soluta ad asperiores ratione molestias. Nisi natus ullam cum alias magni qui, impedit molestias? Facere maiores enim eum iusto perspiciatis minus commodi recusandae placeat est obcaecati.
Aut, accusantium. Facere, beatae ipsam? Eum id recusandae autem perspiciatis nesciunt distinctio voluptatem animi iure voluptatibus, adipisci a consequuntur sunt error architecto repellendus vitae et esse commodi, at, maxime quos!
Eius nesciunt quasi iure. Totam officia quod harum quia error ex maxime inventore corrupti cum dolores? Fugiat, rem quod saepe sapiente deserunt, fugit illo, quia iure deleniti nulla recusandae aliquam.
Distinctio, temporibus harum eaque illum ea esse qui ut fuga ipsam natus maxime nesciunt sed voluptatem rerum quis nulla voluptatum provident quasi, nam praesentium. In id non amet ipsum sequi.
Atque perferendis nihil quam possimus ducimus. Quae quos laudantium voluptate quibusdam dolorum temporibus aperiam, ratione nobis neque reprehenderit, aut tenetur harum unde molestiae in voluptatibus beatae eum! Natus, tenetur voluptas!
Aspernatur delectus magnam beatae, repellat odio praesentium deleniti, placeat fugiat ad, mollitia at dolorem provident eligendi! Nihil quia beatae minus doloribus tempora iste ratione, reprehenderit consequatur, quos rerum sed debitis.
Error, hic. Impedit esse aliquam ipsa similique repellat laboriosam ex. Eligendi cum odit inventore architecto animi ea. Ab quaerat, cum dolorum incidunt adipisci ducimus iure omnis autem perspiciatis aliquam harum.
Eos exercitationem sed nisi culpa, rem commodi harum obcaecati, quo dolores magnam iure quaerat accusantium a doloremque laborum error iste cum. Nemo voluptates id, delectus laborum veritatis repellat repellendus est!
Doloribus quaerat saepe repudiandae praesentium earum nulla dolorum molestiae itaque qui delectus ipsa architecto nam fugiat voluptas tempora vel aspernatur veritatis, voluptates at quae voluptatum? Nihil sit quisquam eum quasi.
Aperiam architecto odit illum eius, ab nostrum expedita accusantium? Tempore id quam adipisci, nobis aliquid ipsa ducimus quae veniam sit unde aspernatur nam eaque vel incidunt dicta perferendis inventore dignissimos?
Eum exercitationem asperiores officia laboriosam earum minus facilis eligendi accusamus nesciunt expedita, dicta sint. Ullam officia repellat asperiores ipsa ea facere atque veniam eaque excepturi, harum est accusantium aut eum.
Autem illo cum, necessitatibus quo, temporibus delectus enim officiis culpa et veritatis vero blanditiis eaque repellat veniam possimus magni voluptas aliquid dolores maxime mollitia est odio pariatur animi explicabo. Fugiat!`,

  `        Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat quam animi nulla quis dignissimos corporis delectus mollitia ducimus libero aut quia, quaerat saepe at officiis error quod, dolore sapiente cupiditate?
        Delectus ab vitae laudantium corporis nulla, pariatur maxime. Soluta repellendus quia atque sit officiis ut non qui, molestias ipsa aliquid incidunt sapiente laboriosam amet at accusamus pariatur reprehenderit minus blanditiis.
        Amet voluptas dignissimos autem facere doloribus quam quaerat eligendi nam sint laboriosam nihil, vitae deserunt officiis fuga, quisquam quos sapiente! In quia perferendis eum dolores, modi incidunt tenetur repellendus itaque!
        Earum ullam facilis molestias. Non facilis officia illum eligendi nesciunt quo qui ratione adipisci debitis excepturi assumenda voluptatum, fugiat ab, tenetur culpa! Fugit molestias nobis, tenetur fugiat quae neque suscipit!
        Quasi quod dolorem, quis assumenda neque, porro deleniti cumque odio voluptas quos explicabo eius accusantium quas asperiores, quae odit perferendis nobis laborum minima! Eos, autem vel laborum labore blanditiis dolorum.
        Cum, quisquam obcaecati? Sit, laborum repellat laudantium sunt est ducimus voluptate, dolor sed alias esse possimus hic ratione delectus ullam id quidem maiores quae veritatis distinctio quis quam, cum tenetur.
        Quos, aut consequuntur assumenda distinctio consequatur praesentium, accusamus sit delectus alias quidem possimus corporis ratione est perferendis nisi quas, dolorem libero recusandae in! Repellendus fuga dolor maiores ullam sed odio.
        Tempore suscipit obcaecati eos ad, quasi nesciunt doloremque sunt itaque dolorum ratione est id corrupti officia sequi dolorem ea quam quisquam eveniet harum pariatur placeat natus! Nobis tempore aperiam accusamus!
        Voluptate natus aspernatur porro libero doloremque, excepturi quidem dignissimos expedita provident consequuntur in voluptatem officiis ullam sunt debitis cupiditate adipisci perspiciatis mollitia! Earum odit voluptates quae sunt optio veniam cum.
        Facere eos ut cupiditate, repellendus, placeat perspiciatis repudiandae officiis neque assumenda maxime minima veritatis magnam fugiat sequi adipisci consectetur temporibus alias expedita unde odio numquam molestiae doloribus modi! Eligendi, laboriosam?
        Odit nesciunt consectetur, ad non repudiandae deserunt optio quis amet at voluptatibus, sint aliquam hic, facilis deleniti eligendi id. Expedita unde quos natus voluptas laborum, omnis voluptate placeat rerum quia.
        Repellendus reiciendis, atque laborum illo illum, laudantium porro commodi itaque corporis amet quia incidunt iusto voluptatem aliquid unde! Soluta rem, aut aperiam magnam corrupti totam commodi suscipit eius doloremque aliquid?
        Libero exercitationem qui excepturi ipsam, nemo placeat! Voluptas dolores animi dolor perferendis fuga accusamus molestias voluptate consequatur quibusdam, doloribus labore, similique deserunt recusandae architecto illum vitae exercitationem quis consectetur? Quas?
        Harum nobis ex, eaque nesciunt quas accusantium suscipit numquam facilis atque dolores temporibus saepe quis, voluptatem itaque iusto magni omnis nihil enim alias dolorem. Ab, dolores dolor. Consequuntur, velit dolorum!
        Exercitationem reiciendis aliquam qui veritatis voluptas enim odit possimus modi, adipisci, animi vitae eveniet quos dicta! Assumenda eius corrupti quis tempore sit facere blanditiis itaque velit? Autem aliquam quae tenetur.
        Iure officia aspernatur enim excepturi adipisci. Temporibus iste cum nostrum accusantium officia cumque nam sed vero tempora ipsam, autem necessitatibus optio commodi deleniti quasi dicta officiis saepe, provident possimus sit!
        Adipisci earum quis sint similique consequuntur placeat aut nostrum voluptatibus deleniti doloremque ipsum optio in amet illo corrupti libero iste modi quam, recusandae quia rem. Distinctio dolore molestiae debitis unde!
        Error, in earum laboriosam ullam iusto ducimus deleniti hic dignissimos aperiam totam nulla asperiores? Doloremque, porro voluptatibus voluptate illo atque, ipsum dolorem vero laudantium aspernatur ea quia saepe tenetur aliquid?
        Alias nulla qui, illo incidunt dolore placeat minima aspernatur assumenda magni, id expedita. Deleniti dolor minima at amet, sunt dolorum accusantium nulla temporibus aliquid soluta quos deserunt omnis ipsum quasi.
        Perferendis rem, distinctio provident sed, hic ratione blanditiis nesciunt sit quos esse quod officiis illo quibusdam, molestiae ut tempore quae voluptates laborum ducimus tempora repudiandae reiciendis fugit expedita. Tempora, impedit?
        Consequuntur incidunt voluptatem harum reprehenderit non amet aliquid obcaecati aspernatur veritatis vitae minus, eos ab, unde dolore repudiandae. Tempora esse repellendus dignissimos voluptatem reiciendis ut, at quo ea quae tempore.
        Sint quibusdam aperiam natus fuga sit fugit, reprehenderit suscipit doloremque temporibus, atque facilis consectetur quisquam veniam eos, est minima facere nemo magnam exercitationem fugiat ducimus tempora dolorem! Repellat, totam sed.
        Iste eum ipsam neque optio molestiae molestias. Nam praesentium eos, sequi accusamus dolorem incidunt laboriosam voluptate quas fugit architecto voluptates voluptatum quisquam, ex, officia quis alias perspiciatis dolores porro adipisci.
        Eligendi rem cum nostrum sint laborum quam. Architecto, ipsa obcaecati fuga libero provident aliquid dolorum esse. Tempora culpa placeat provident aperiam. Inventore nostrum optio odit incidunt dolor omnis asperiores officia.
        Nesciunt reiciendis autem, laboriosam eos odio magni exercitationem eum sit numquam quo dolores laudantium. Sint incidunt numquam doloribus nobis atque enim porro, officia quidem fuga facilis veniam laboriosam corporis dolore?
        Recusandae excepturi totam sint commodi obcaecati fuga repudiandae rerum modi, tempora qui quisquam eos natus corporis doloremque unde, ea culpa vitae est adipisci deserunt nam iure sit numquam id. Molestiae.
        Dolore dolores odit ad, quia, officia ex delectus nisi reiciendis inventore quos voluptates laudantium magni ab amet error quaerat excepturi iure eligendi. Eius deleniti ipsum assumenda ratione eaque. Facilis, fugit!
        Molestiae illum, repellendus aliquid velit deserunt reiciendis temporibus esse eius dolor optio a fugit nostrum laudantium consequuntur, expedita distinctio sunt tempora aperiam excepturi ipsa impedit dignissimos ab debitis. Officia, vitae.
        Accusantium, maiores nobis voluptas expedita quis aspernatur velit. Dolor ducimus laboriosam beatae. Error quidem eaque aperiam ipsa sequi sapiente quis quasi minus odio, nostrum necessitatibus explicabo dolorem, illo voluptates ut!
        Perspiciatis officia modi quas ipsam dignissimos, error quisquam soluta voluptates nostrum assumenda quo eum nulla nisi dolorem culpa veniam ipsa quia provident exercitationem laborum reprehenderit hic. Architecto suscipit laboriosam quam?
        Similique alias, enim praesentium eum iste repellat ut dignissimos, sapiente architecto vitae velit? Vero, adipisci repellendus blanditiis quas maxime excepturi optio similique placeat veniam explicabo odio ab porro soluta? Explicabo.
        Sint aspernatur ipsam provident atque debitis unde rem quam iure architecto exercitationem nulla sequi, similique quibusdam enim, laboriosam incidunt! Ullam placeat reiciendis libero, quia voluptas laboriosam eveniet atque corrupti fuga?
        Magni quaerat odio modi iste blanditiis. Voluptates architecto optio distinctio praesentium cum, dolorum similique eveniet culpa odit repudiandae omnis quod doloremque corrupti iste exercitationem iure pariatur quaerat? Culpa, voluptate in.
        Commodi, praesentium adipisci? Aspernatur impedit, incidunt ipsa labore nulla iure facere tempora? Nihil sunt illo magni delectus facere laudantium facilis aspernatur, aliquam inventore voluptas, quaerat veniam? Tempora sint neque quis!
        Ut ullam natus laboriosam, blanditiis nulla eius quam illum inventore fugiat modi maiores molestiae placeat sequi tenetur dolore? Et necessitatibus reiciendis nisi odit reprehenderit nihil similique id fuga porro cupiditate.
        Dolore quidem quia perspiciatis molestiae itaque unde nesciunt laborum animi cumque, laboriosam sed sunt beatae necessitatibus quos earum maiores quam explicabo quis blanditiis recusandae eveniet pariatur consectetur. Veritatis, voluptates dignissimos.
        Aliquid necessitatibus fugit quas praesentium quasi cum magni placeat vero esse eius officiis a, accusantium earum molestias perferendis voluptatibus, sit repellendus facilis omnis numquam repellat! Cupiditate accusantium iusto soluta error?
        Nostrum quis autem nulla quam sint cupiditate, quaerat asperiores quidem voluptate praesentium inventore adipisci perspiciatis ipsa eligendi reprehenderit quo ullam. Obcaecati quam consectetur magnam laborum eos facere commodi optio iure.
        Dolorum ea, magnam quisquam vitae ad provident voluptatem veritatis consequatur eveniet iure, mollitia dignissimos ut cum quia laudantium quaerat eaque quam nihil dolore. Repudiandae similique commodi tempora exercitationem necessitatibus neque.
        A quidem asperiores sint nisi quasi corrupti inventore illo qui, hic in magnam dolor perferendis facere esse nobis cumque. Dolorum sequi consequuntur possimus! Quas incidunt voluptas illo obcaecati. Atque, necessitatibus.`,

  `        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, esse cupiditate. Sed amet labore magni ab nihil voluptates accusamus cupiditate, delectus veniam minima earum temporibus odit, perferendis nostrum. Asperiores, rem.
        Perspiciatis dolore possimus dolor alias iste sed quam magni. Et earum quaerat sed, repudiandae dolore dolorum, vero, eligendi aut modi eveniet veniam sint at porro asperiores doloremque odit enim provident.
        Dicta asperiores reiciendis ab sint quaerat, enim repudiandae, autem, eaque minus odit delectus molestiae incidunt impedit sed magnam omnis facere facilis. Nisi deserunt quia animi delectus aliquid culpa doloremque fugiat!
        Iure labore magnam dicta praesentium, blanditiis assumenda. Quis velit veritatis commodi dolore ducimus explicabo totam, architecto dignissimos quod esse quia dolorum voluptatum inventore tempora quisquam aut eveniet voluptates pariatur porro?
        Quae deleniti aperiam eveniet impedit numquam rem animi, eos amet, magni provident voluptatibus alias neque enim temporibus. Adipisci debitis quae, earum aspernatur temporibus repellat, mollitia odio, asperiores consequatur accusamus eum.
        Dolore laboriosam magnam expedita tempore sequi et eos eum harum animi, soluta recusandae pariatur at esse non facilis minima voluptates rerum ea totam perferendis. Eaque earum eum omnis ea numquam!
        Facilis hic maiores odit adipisci perspiciatis quisquam et vel magni odio. Quaerat exercitationem aliquid nemo ratione molestiae, aliquam quae aut necessitatibus repellat ipsam omnis esse officia in soluta ad rerum.
        Reiciendis consequuntur enim ducimus temporibus in itaque at. Provident sed repudiandae, est ipsam eius fugit ullam eligendi accusantium ab illo aliquid voluptatum, hic tempora. Magnam commodi ducimus tenetur dolor repudiandae.
        Asperiores dolorem nemo numquam maxime nobis aspernatur omnis, sint consectetur quibusdam recusandae officiis possimus eum exercitationem itaque delectus unde. Quidem suscipit optio nesciunt vitae pariatur iusto aliquam aperiam corrupti velit!
        Quas eveniet odit ipsa eos quos. Cupiditate cumque, eligendi quasi voluptatibus beatae dolores dolor, voluptatem illum quae similique eum error libero corporis? Nesciunt a ipsa impedit dolor. Consequatur, debitis! Quos.
        Tempora recusandae consequuntur nemo, asperiores magnam culpa cumque libero necessitatibus ipsam rem eos excepturi minima soluta tempore dolorem repellat. Esse suscipit fugit minima quasi veniam exercitationem alias ducimus natus ullam?
        Explicabo voluptas reiciendis aliquam aspernatur perferendis harum, nam eum quibusdam facere nesciunt suscipit voluptatem laudantium unde, porro eius eveniet quae maxime? Repellat fugit nam tempore reiciendis nihil eos, possimus libero.
        Enim illum, excepturi molestias facilis voluptatibus, consequuntur, cumque officia sunt dolorem ipsum laudantium. Tempora possimus et ea quaerat omnis. Dolorem sed eius vitae nihil rem natus accusamus debitis iste voluptate.
        Voluptates iste, quas iusto quia nisi eaque placeat esse, recusandae unde exercitationem ullam, temporibus eveniet at quasi illo ex autem expedita vero? Cum hic labore atque esse placeat minus voluptatibus.
        Nam illum consequatur facere dolorem minus, aut ea porro sunt esse rerum. Amet voluptates hic eius similique laborum architecto saepe reprehenderit non facere consequatur unde autem itaque, distinctio vitae tenetur.
        Molestias tenetur odit corrupti odio, numquam labore vel atque at. Possimus, beatae delectus adipisci nemo suscipit deserunt eveniet sint modi aperiam inventore, reprehenderit dolorum quae quas voluptatem blanditiis quisquam magnam?
        Vitae voluptates tenetur itaque ipsa mollitia assumenda veritatis doloribus ea earum minus! Sunt cupiditate illo reiciendis voluptatum odit! Asperiores laborum blanditiis sapiente omnis dolores expedita voluptates aperiam, voluptatibus eveniet ad.
        Ipsam qui laboriosam nam totam? Expedita animi dolore, dolores voluptate ex omnis. Explicabo illo atque cumque iste? Ullam, rem nam voluptatem dolorem sequi sunt quod cum amet saepe totam libero!
        Porro excepturi eaque ex delectus eius, laboriosam nesciunt, assumenda quibusdam, illum laudantium neque? Facilis sit quis temporibus quos et voluptatem unde est, adipisci recusandae ratione repellat accusantium eaque id sapiente?
        Quos et veniam iusto debitis cupiditate exercitationem pariatur est! Atque ipsam dolor suscipit quis quibusdam optio, voluptatum nisi, in repellendus reiciendis assumenda iure nostrum at sed iste laboriosam quia exercitationem.
        Deserunt ducimus culpa ab ut minus fugit nisi blanditiis accusamus ipsa doloribus, totam, eligendi expedita dolor aperiam nam amet recusandae perferendis suscipit nobis nesciunt quasi rerum itaque, et ipsum. Dolore!
        Nostrum, quos adipisci molestiae labore veritatis nulla molestias aperiam reiciendis doloribus voluptatum non facilis quibusdam provident inventore ratione, vero quaerat tempore maxime ducimus obcaecati repudiandae eveniet. Voluptas harum sint ad.
        Rem tenetur neque maiores eos veritatis, ad dolorem est velit enim pariatur beatae temporibus dolore blanditiis, at reprehenderit vitae aut iste ipsum voluptas obcaecati! Libero placeat reiciendis nulla nostrum? Ut.
        Iste alias similique laboriosam vitae pariatur modi aspernatur enim repellendus suscipit commodi in est nemo reiciendis, consequatur ipsam et, non repellat officia praesentium! Repellat modi nihil molestiae quasi, facilis aliquid?
        Tempora placeat explicabo ipsa, alias, excepturi id, unde dolor sunt aperiam suscipit optio et adipisci repellat. Cum expedita impedit non rerum, odio, totam eveniet quae corrupti inventore repellendus, itaque quas!
        Officiis obcaecati laborum dolorum exercitationem rem a voluptate aliquam, consectetur cumque iusto commodi! Reprehenderit esse laboriosam beatae recusandae id, consectetur dicta nisi nesciunt architecto non modi ipsam rerum animi reiciendis.
        Voluptates ab eligendi, tempora amet excepturi optio asperiores nesciunt maiores repudiandae provident tempore doloremque ex officia magni voluptatum maxime? Illo quisquam harum sequi accusamus eos placeat. Adipisci, nemo facilis. Amet!
        Earum necessitatibus consequuntur id tempore aperiam omnis nulla sed aut doloremque quisquam sunt quaerat doloribus fugit accusantium, culpa amet velit odio accusamus, quas expedita asperiores officia eligendi beatae ipsa. Voluptas.
        Dignissimos ad tempora nemo ipsum consequuntur maiores soluta! Facilis, maiores fugit. Quibusdam, nesciunt voluptate error in impedit facilis quae, rem quidem eligendi placeat blanditiis esse quis voluptas repellat dolorem totam.
        Repudiandae dignissimos modi, dolor iure maiores ea neque minima laborum aut? Non, dignissimos sint? Enim amet ipsam sequi, aperiam esse quo commodi quam earum suscipit soluta iste vero natus distinctio!
        Ad quae odio rem nemo expedita quis excepturi ex consequuntur nisi. Non debitis assumenda cum iusto optio iste placeat excepturi ut recusandae est deleniti quasi, atque, deserunt autem aut reiciendis.
        Consectetur natus optio deleniti porro laboriosam ex quae fugiat eveniet? Accusamus aut quos magnam, deleniti et voluptatem sint quam quo quis animi facilis totam labore consectetur accusantium, aliquam possimus aliquid!
        Id voluptate, quidem sapiente ratione itaque accusantium numquam explicabo excepturi aspernatur, aperiam voluptatem commodi. Mollitia quae, consequatur ipsum laborum animi totam a beatae eius fugit autem hic impedit officia eveniet!
        Labore, expedita praesentium. Veniam delectus enim nostrum atque dolorem similique non est maxime ducimus, officiis laudantium autem fuga maiores dolorum totam! Dicta rerum dolores ipsa odio quaerat blanditiis similique dolorum?
        Eligendi similique sint quidem. Dolor molestiae sapiente explicabo porro numquam sit, in architecto, qui voluptatem veritatis ullam tenetur. Libero delectus facilis quasi aut! Fugit deserunt explicabo corporis dolorum repudiandae qui.
        Quia officia, earum a cumque, sapiente nesciunt ea fugiat harum hic, corporis explicabo. Et ex corrupti eveniet neque veniam cumque suscipit sed? Recusandae nobis asperiores suscipit quis, voluptatum corrupti consequatur!
        Pariatur, id. Fuga ex magni esse amet ea explicabo facilis odit. Voluptatem animi eveniet repellat doloremque corrupti nesciunt inventore, numquam, repudiandae, incidunt dolores quos assumenda minus tempora quod in sapiente?
        Quos nemo iste vero, ipsam nesciunt debitis fugit, id eius voluptatibus voluptas nam laudantium cupiditate perspiciatis sequi itaque ab architecto natus est magni unde modi pariatur? Ad, cupiditate? Nam, voluptate.
        Molestias eos itaque nulla blanditiis, quisquam hic ipsam pariatur fugiat dolore facilis! Nobis molestiae, veritatis a eum vel error dicta, corporis deserunt ab nam fugiat ratione odio voluptates aut sint!
        Corrupti architecto saepe debitis temporibus hic voluptatum consequuntur molestias beatae inventore aliquam ipsam quis laboriosam alias quos explicabo sed, obcaecati expedita, error quia nulla repudiandae cum libero possimus? Necessitatibus, possimus.`,
];

const container = document.getElementById("container-element");
const previewElement = document.getElementById("preview-element");
const textElement = document.getElementById("text-element");
const audio = new Audio("./assets/badapple.mp3");

const updateText = () => {
  const randomText = Math.floor(Math.random() * letters.length);
  textElement.textContent = letters[randomText];
};

const start = () => {
  audio.play();
  setTimeout(() => {
    container.style.backgroundImage = "url('./assets/badapple.gif')";
    previewElement.src = "./assets/badapple.gif";
  }, 500);
  setInterval(updateText, 30);
  window.removeEventListener("click", start);
};

audio.loop = true;

window.addEventListener("click", start);
